# .github/workflows/check_iptv.yml

name: Check IPTV Sources

on:
  push:
    branches:
      - main
    paths:
      - 'iptv.txt'
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间午夜运行
  workflow_dispatch: # 允许手动触发

jobs:
  check-sources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check IPTV links
        id: check_links
        run: |
          output_file="output.txt"
          temp_file="temp_output.txt"
          
          echo -n "" > "$temp_file"
          echo "Starting to check IPTV links..."
          
          while IFS=',' read -r name url; do
            if [[ -z "$name" || "$name" =~ ^# ]]; then
              continue
            fi
            
            # 使用 Bash 内置的参数扩展来去除字符串前后的空格
            # 这是最安全的方法，因为它不会受到引号的影响
            name="${name// /}"
            url="${url// /}"

            echo "Checking: $name - $url"
            
            http_code=$(curl -s -o /dev/null -w "%{http_code}" -m 10 "$url" || true)
            
            if [[ "$http_code" -eq 200 ]]; then
              echo "✅ Valid: $name - $url"
              echo "$name,$url" >> "$temp_file"
            else
              echo "❌ Invalid: $name - $url (HTTP Status: $http_code)"
            fi
          done < iptv.txt
          
          echo "Sorting and saving valid links to output.txt..."
          sort "$temp_file" -o "$output_file"
          
          if git diff --exit-code "$output_file"; then
            echo "No changes in output.txt, skipping commit."
            echo "::set-output name=has_changes::false"
          else
            echo "Changes detected in output.txt, preparing to commit."
            echo "::set-output name=has_changes::true"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$output_file"
            git commit -m "Update output.txt with valid IPTV sources"
          fi
        shell: bash
        
      - name: Push changes
        if: steps.check_links.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
